2024-03-04 15:23:07 â€” INFO â€” Running with edr=0.14.1
2024-03-04 15:23:07 â€” INFO â€” Installing packages for edr internal dbt package...
2024-03-04 15:23:07 â€” INFO â€” Running dbt --log-format json deps --project-dir /Users/boladefidipe/Desktop/dbt-sf/dbt-env/lib/python3.11/site-packages/elementary/monitor/dbt_project
2024-03-04 15:23:10 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'deps', '--project-dir', '/Users/boladefidipe/Desktop/dbt-sf/dbt-env/lib/python3.11/site-packages/elementary/monitor/dbt_project']' is 3430
2024-03-04 15:23:10 â€” INFO â€” Running with dbt=1.7.9
2024-03-04 15:23:10 â€” INFO â€” Updating lock file in file path: /Users/boladefidipe/Desktop/dbt-sf/dbt-env/lib/python3.11/site-packages/elementary/monitor/dbt_project/package-lock.yml
2024-03-04 15:23:10 â€” INFO â€” Installing dbt-labs/dbt_utils
2024-03-04 15:23:10 â€” INFO â€” Installed from version 0.8.6
2024-03-04 15:23:10 â€” INFO â€” Updated version available: 1.1.1
2024-03-04 15:23:10 â€” INFO â€” Installing elementary-data/elementary
2024-03-04 15:23:10 â€” INFO â€” Installed from version 0.14.1
2024-03-04 15:23:10 â€” INFO â€” Up to date!
2024-03-04 15:23:10 â€” INFO â€” 
2024-03-04 15:23:10 â€” INFO â€” Updates available for packages: ['dbt-labs/dbt_utils']                 
Update your versions in packages.yml, then run dbt deps
2024-03-04 15:23:10 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_latest_invocation", "macro_args": {}} --project-dir /Users/boladefidipe/Desktop/dbt-sf/dbt-env/lib/python3.11/site-packages/elementary/monitor/dbt_project
[31;20m2024-03-04 15:23:14 â€” ERROR â€” Unable to get the latest invocation: Failed to run dbt command.
Encountered an error while running operation: Database Error
  250001 (08001): Failed to connect to DB: ju72694.europe-west2.gcp.snowflakecomputing.com:443. Incorrect username or password was specified.[0m
2024-03-04 15:23:14 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_adapter_type_and_unique_id", "macro_args": {}} --project-dir /Users/boladefidipe/Desktop/dbt-sf/dbt-env/lib/python3.11/site-packages/elementary/monitor/dbt_project
2024-03-04 15:23:16 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_adapter_type_and_unique_id", "macro_args": {}}', '--project-dir', '/Users/boladefidipe/Desktop/dbt-sf/dbt-env/lib/python3.11/site-packages/elementary/monitor/dbt_project']' is 1903
2024-03-04 15:23:16 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_elementary_database_and_schema", "macro_args": {}} --project-dir /Users/boladefidipe/Desktop/dbt-sf/dbt-env/lib/python3.11/site-packages/elementary/monitor/dbt_project
2024-03-04 15:23:18 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_elementary_database_and_schema", "macro_args": {}}', '--project-dir', '/Users/boladefidipe/Desktop/dbt-sf/dbt-env/lib/python3.11/site-packages/elementary/monitor/dbt_project']' is 1867
2024-03-04 15:23:18 â€” INFO â€” Elementary's database and schema: '"DBT_DEMO.DEV_elementary"'
2024-03-04 15:23:18 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_test_results", "macro_args": {"days_back": 7, "invocations_per_test": 720, "disable_passed_test_metrics": false}} --project-dir /Users/boladefidipe/Desktop/dbt-sf/dbt-env/lib/python3.11/site-packages/elementary/monitor/dbt_project
[31;20m2024-03-04 15:23:21 â€” ERROR â€” Could not generate the report - Error: Failed to run dbt command.
Encountered an error while running operation: Database Error
  250001 (08001): Failed to connect to DB: ju72694.europe-west2.gcp.snowflakecomputing.com:443. Incorrect username or password was specified.
Please reach out to our community for help with this issue.[0m
Traceback (most recent call last):
  File "/Users/boladefidipe/Desktop/dbt-sf/dbt-env/lib/python3.11/site-packages/elementary/clients/dbt/dbt_runner.py", line 88, in _run_command
    result = subprocess.run(
             ^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_test_results", "macro_args": {"days_back": 7, "invocations_per_test": 720, "disable_passed_test_metrics": false}}', '--project-dir', '/Users/boladefidipe/Desktop/dbt-sf/dbt-env/lib/python3.11/site-packages/elementary/monitor/dbt_project']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/boladefidipe/Desktop/dbt-sf/dbt-env/lib/python3.11/site-packages/elementary/monitor/api/report/report.py", line 50, in get_report_data
    tests_api = TestsAPI(
                ^^^^^^^^^
  File "/Users/boladefidipe/Desktop/dbt-sf/dbt-env/lib/python3.11/site-packages/elementary/monitor/api/tests/tests.py", line 39, in __init__
    self.test_results_db_rows = self._get_test_results_db_rows(
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/boladefidipe/Desktop/dbt-sf/dbt-env/lib/python3.11/site-packages/elementary/monitor/api/tests/tests.py", line 51, in _get_test_results_db_rows
    return self.tests_fetcher.get_all_test_results_db_rows(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/boladefidipe/Desktop/dbt-sf/dbt-env/lib/python3.11/site-packages/elementary/monitor/fetchers/tests/tests.py", line 22, in get_all_test_results_db_rows
    run_operation_response = self.dbt_runner.run_operation(
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/boladefidipe/Desktop/dbt-sf/dbt-env/lib/python3.11/site-packages/elementary/clients/dbt/dbt_runner.py", line 160, in run_operation
    success, command_output = self._run_command(
                              ^^^^^^^^^^^^^^^^^^
  File "/Users/boladefidipe/Desktop/dbt-sf/dbt-env/lib/python3.11/site-packages/elementary/clients/dbt/dbt_runner.py", line 99, in _run_command
    raise DbtCommandError(err, command_args, logs=logs)
elementary.exceptions.exceptions.DbtCommandError: Failed to run dbt command.
Encountered an error while running operation: Database Error
  250001 (08001): Failed to connect to DB: ju72694.europe-west2.gcp.snowflakecomputing.com:443. Incorrect username or password was specified.
2024-03-04 15:23:57 â€” INFO â€” Running with edr=0.14.1
2024-03-04 15:23:57 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_latest_invocation", "macro_args": {}} --project-dir /Users/boladefidipe/Desktop/dbt-sf/dbt-env/lib/python3.11/site-packages/elementary/monitor/dbt_project
[31;20m2024-03-04 15:23:59 â€” ERROR â€” Unable to get the latest invocation: Failed to run dbt command.
Encountered an error while running operation: Database Error
  250001 (08001): Failed to connect to DB: ju72694.europe-west2.gcp.snowflakecomputing.com:443. Incorrect username or password was specified.[0m
2024-03-04 15:23:59 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_adapter_type_and_unique_id", "macro_args": {}} --project-dir /Users/boladefidipe/Desktop/dbt-sf/dbt-env/lib/python3.11/site-packages/elementary/monitor/dbt_project
2024-03-04 15:24:01 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_adapter_type_and_unique_id", "macro_args": {}}', '--project-dir', '/Users/boladefidipe/Desktop/dbt-sf/dbt-env/lib/python3.11/site-packages/elementary/monitor/dbt_project']' is 1903
2024-03-04 15:24:01 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_elementary_database_and_schema", "macro_args": {}} --project-dir /Users/boladefidipe/Desktop/dbt-sf/dbt-env/lib/python3.11/site-packages/elementary/monitor/dbt_project
2024-03-04 15:24:03 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_elementary_database_and_schema", "macro_args": {}}', '--project-dir', '/Users/boladefidipe/Desktop/dbt-sf/dbt-env/lib/python3.11/site-packages/elementary/monitor/dbt_project']' is 1867
2024-03-04 15:24:03 â€” INFO â€” Elementary's database and schema: '"DBT_DEMO.DEV_elementary"'
2024-03-04 15:24:03 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_test_results", "macro_args": {"days_back": 7, "invocations_per_test": 720, "disable_passed_test_metrics": false}} --project-dir /Users/boladefidipe/Desktop/dbt-sf/dbt-env/lib/python3.11/site-packages/elementary/monitor/dbt_project
[31;20m2024-03-04 15:24:05 â€” ERROR â€” Could not generate the report - Error: Failed to run dbt command.
Encountered an error while running operation: Database Error
  250001 (08001): Failed to connect to DB: ju72694.europe-west2.gcp.snowflakecomputing.com:443. Incorrect username or password was specified.
Please reach out to our community for help with this issue.[0m
Traceback (most recent call last):
  File "/Users/boladefidipe/Desktop/dbt-sf/dbt-env/lib/python3.11/site-packages/elementary/clients/dbt/dbt_runner.py", line 88, in _run_command
    result = subprocess.run(
             ^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_test_results", "macro_args": {"days_back": 7, "invocations_per_test": 720, "disable_passed_test_metrics": false}}', '--project-dir', '/Users/boladefidipe/Desktop/dbt-sf/dbt-env/lib/python3.11/site-packages/elementary/monitor/dbt_project']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/boladefidipe/Desktop/dbt-sf/dbt-env/lib/python3.11/site-packages/elementary/monitor/api/report/report.py", line 50, in get_report_data
    tests_api = TestsAPI(
                ^^^^^^^^^
  File "/Users/boladefidipe/Desktop/dbt-sf/dbt-env/lib/python3.11/site-packages/elementary/monitor/api/tests/tests.py", line 39, in __init__
    self.test_results_db_rows = self._get_test_results_db_rows(
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/boladefidipe/Desktop/dbt-sf/dbt-env/lib/python3.11/site-packages/elementary/monitor/api/tests/tests.py", line 51, in _get_test_results_db_rows
    return self.tests_fetcher.get_all_test_results_db_rows(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/boladefidipe/Desktop/dbt-sf/dbt-env/lib/python3.11/site-packages/elementary/monitor/fetchers/tests/tests.py", line 22, in get_all_test_results_db_rows
    run_operation_response = self.dbt_runner.run_operation(
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/boladefidipe/Desktop/dbt-sf/dbt-env/lib/python3.11/site-packages/elementary/clients/dbt/dbt_runner.py", line 160, in run_operation
    success, command_output = self._run_command(
                              ^^^^^^^^^^^^^^^^^^
  File "/Users/boladefidipe/Desktop/dbt-sf/dbt-env/lib/python3.11/site-packages/elementary/clients/dbt/dbt_runner.py", line 99, in _run_command
    raise DbtCommandError(err, command_args, logs=logs)
elementary.exceptions.exceptions.DbtCommandError: Failed to run dbt command.
Encountered an error while running operation: Database Error
  250001 (08001): Failed to connect to DB: ju72694.europe-west2.gcp.snowflakecomputing.com:443. Incorrect username or password was specified.
2024-03-04 15:26:43 â€” INFO â€” Running with edr=0.14.1
2024-03-04 15:26:43 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_latest_invocation", "macro_args": {}} --project-dir /Users/boladefidipe/Desktop/dbt-sf/dbt-env/lib/python3.11/site-packages/elementary/monitor/dbt_project
2024-03-04 15:26:48 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_latest_invocation", "macro_args": {}}', '--project-dir', '/Users/boladefidipe/Desktop/dbt-sf/dbt-env/lib/python3.11/site-packages/elementary/monitor/dbt_project']' is 4334
2024-03-04 15:26:48 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_adapter_type_and_unique_id", "macro_args": {}} --project-dir /Users/boladefidipe/Desktop/dbt-sf/dbt-env/lib/python3.11/site-packages/elementary/monitor/dbt_project
2024-03-04 15:26:50 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_adapter_type_and_unique_id", "macro_args": {}}', '--project-dir', '/Users/boladefidipe/Desktop/dbt-sf/dbt-env/lib/python3.11/site-packages/elementary/monitor/dbt_project']' is 1903
2024-03-04 15:26:50 â€” INFO â€” edr (0.14.1) and Elementary's dbt package (0.14.1) are compatible.
2024-03-04 15:26:50 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_elementary_database_and_schema", "macro_args": {}} --project-dir /Users/boladefidipe/Desktop/dbt-sf/dbt-env/lib/python3.11/site-packages/elementary/monitor/dbt_project
2024-03-04 15:26:52 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_elementary_database_and_schema", "macro_args": {}}', '--project-dir', '/Users/boladefidipe/Desktop/dbt-sf/dbt-env/lib/python3.11/site-packages/elementary/monitor/dbt_project']' is 1867
2024-03-04 15:26:52 â€” INFO â€” Elementary's database and schema: '"DBT_DEMO.DEV_elementary"'
2024-03-04 15:26:52 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_test_results", "macro_args": {"days_back": 7, "invocations_per_test": 720, "disable_passed_test_metrics": false}} --project-dir /Users/boladefidipe/Desktop/dbt-sf/dbt-env/lib/python3.11/site-packages/elementary/monitor/dbt_project
2024-03-04 15:26:56 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_test_results", "macro_args": {"days_back": 7, "invocations_per_test": 720, "disable_passed_test_metrics": false}}', '--project-dir', '/Users/boladefidipe/Desktop/dbt-sf/dbt-env/lib/python3.11/site-packages/elementary/monitor/dbt_project']' is 26925
2024-03-04 15:26:56 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_source_freshness_results", "macro_args": {"days_back": 7, "invocations_per_test": 720}} --project-dir /Users/boladefidipe/Desktop/dbt-sf/dbt-env/lib/python3.11/site-packages/elementary/monitor/dbt_project
2024-03-04 15:26:58 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_source_freshness_results", "macro_args": {"days_back": 7, "invocations_per_test": 720}}', '--project-dir', '/Users/boladefidipe/Desktop/dbt-sf/dbt-env/lib/python3.11/site-packages/elementary/monitor/dbt_project']' is 1817
2024-03-04 15:26:58 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_models", "macro_args": {"exclude_elementary": true}} --project-dir /Users/boladefidipe/Desktop/dbt-sf/dbt-env/lib/python3.11/site-packages/elementary/monitor/dbt_project
2024-03-04 15:27:01 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_models", "macro_args": {"exclude_elementary": true}}', '--project-dir', '/Users/boladefidipe/Desktop/dbt-sf/dbt-env/lib/python3.11/site-packages/elementary/monitor/dbt_project']' is 3615
2024-03-04 15:27:01 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_sources", "macro_args": {}} --project-dir /Users/boladefidipe/Desktop/dbt-sf/dbt-env/lib/python3.11/site-packages/elementary/monitor/dbt_project
2024-03-04 15:27:04 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_sources", "macro_args": {}}', '--project-dir', '/Users/boladefidipe/Desktop/dbt-sf/dbt-env/lib/python3.11/site-packages/elementary/monitor/dbt_project']' is 1817
2024-03-04 15:27:04 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_exposures", "macro_args": {}} --project-dir /Users/boladefidipe/Desktop/dbt-sf/dbt-env/lib/python3.11/site-packages/elementary/monitor/dbt_project
2024-03-04 15:27:07 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_exposures", "macro_args": {}}', '--project-dir', '/Users/boladefidipe/Desktop/dbt-sf/dbt-env/lib/python3.11/site-packages/elementary/monitor/dbt_project']' is 1817
2024-03-04 15:27:07 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_models_runs", "macro_args": {"days_back": 7, "exclude_elementary": true}} --project-dir /Users/boladefidipe/Desktop/dbt-sf/dbt-env/lib/python3.11/site-packages/elementary/monitor/dbt_project
2024-03-04 15:27:10 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_models_runs", "macro_args": {"days_back": 7, "exclude_elementary": true}}', '--project-dir', '/Users/boladefidipe/Desktop/dbt-sf/dbt-env/lib/python3.11/site-packages/elementary/monitor/dbt_project']' is 4447
2024-03-04 15:27:10 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_dbt_models_test_coverage", "macro_args": {}} --project-dir /Users/boladefidipe/Desktop/dbt-sf/dbt-env/lib/python3.11/site-packages/elementary/monitor/dbt_project
2024-03-04 15:27:12 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_dbt_models_test_coverage", "macro_args": {}}', '--project-dir', '/Users/boladefidipe/Desktop/dbt-sf/dbt-env/lib/python3.11/site-packages/elementary/monitor/dbt_project']' is 2227
2024-03-04 15:27:12 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_nodes_depends_on_nodes", "macro_args": {"exclude_elementary": true}} --project-dir /Users/boladefidipe/Desktop/dbt-sf/dbt-env/lib/python3.11/site-packages/elementary/monitor/dbt_project
2024-03-04 15:27:15 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_nodes_depends_on_nodes", "macro_args": {"exclude_elementary": true}}', '--project-dir', '/Users/boladefidipe/Desktop/dbt-sf/dbt-env/lib/python3.11/site-packages/elementary/monitor/dbt_project']' is 2451
2024-03-04 15:27:15 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_models_latest_invocation", "macro_args": {}} --project-dir /Users/boladefidipe/Desktop/dbt-sf/dbt-env/lib/python3.11/site-packages/elementary/monitor/dbt_project
2024-03-04 15:27:18 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_models_latest_invocation", "macro_args": {}}', '--project-dir', '/Users/boladefidipe/Desktop/dbt-sf/dbt-env/lib/python3.11/site-packages/elementary/monitor/dbt_project']' is 9383
2024-03-04 15:27:18 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_models_latest_invocations_data", "macro_args": {}} --project-dir /Users/boladefidipe/Desktop/dbt-sf/dbt-env/lib/python3.11/site-packages/elementary/monitor/dbt_project
2024-03-04 15:27:20 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_models_latest_invocations_data", "macro_args": {}}', '--project-dir', '/Users/boladefidipe/Desktop/dbt-sf/dbt-env/lib/python3.11/site-packages/elementary/monitor/dbt_project']' is 2239
